"""
SURU AI — Test Suite for Sports Date Resolution & Voice Output Sanitization.

Verifies:
1. Explicit dates (Sep 28, Sep 29, Sep 30, Oct 1, today, tomorrow, yesterday, weekends, weekdays)
   are extracted accurately and do not collapse to today.
2. Different explicit dates produce distinct provider results without stale cache/filter leakage.
3. Spoken summaries are clean, human-like, and never contain slashes (e.g. Asia/Kolkata),
   pipes, markdown tables, or raw machine syntax.
4. Generic handling across multiple sports (cricket, basketball, tennis, soccer).
"""

import pytest
from datetime import datetime, timezone
from backend.tools.date_parser import parse_date_intent
from backend.tools.sports import SportsTool
from backend.providers.base import MockProvider


@pytest.mark.asyncio
async def test_date_parser_intent_variations():
    """Verify that various natural language date formats resolve accurately."""
    ref_date = "2026-09-30"

    cases = [
        ("What matches are scheduled for September 28?", "2026-09-28", None),
        ("What matches are scheduled for September 29?", "2026-09-29", None),
        ("What matches are on September 30?", "2026-09-30", None),
        ("What matches are on October 1?", "2026-10-01", None),
        ("tell me today's matches", "2026-09-30", None),
        ("show tomorrow's games", "2026-10-01", None),
        ("what happened yesterday?", "2026-09-29", None),
        ("what matches are this weekend?", "2026-10-03", "2026-10-04"),
        ("games next weekend", "2026-10-10", "2026-10-11"),
        ("matches next Monday", "2026-10-12", None),
        ("matches next Friday", "2026-10-09", None),
        ("matches between Sep 28 and Sep 30", "2026-09-28", "2026-09-30"),
        ("fixtures from September 28 to October 2", "2026-09-28", "2026-10-02"),
        ("matches on September 29", "2026-09-29", None),
    ]

    for text, expected_from, expected_to in cases:
        d_from, d_to = parse_date_intent(text, ref_date)
        assert d_from == expected_from, f"Failed date_from for '{text}': expected {expected_from}, got {d_from}"
        assert d_to == expected_to, f"Failed date_to for '{text}': expected {expected_to}, got {d_to}"


@pytest.mark.asyncio
async def test_distinct_dates_produce_distinct_fixtures():
    """Verify that querying Sep 28 vs Sep 29 vs Sep 30 produces distinct fixture sets."""
    res_28 = await SportsTool.fetch_fixtures({"date_from": "2026-09-28", "timezone": "Asia/Kolkata"})
    res_29 = await SportsTool.fetch_fixtures({"date_from": "2026-09-29", "timezone": "Asia/Kolkata"})
    res_30 = await SportsTool.fetch_fixtures({"date_from": "2026-09-30", "timezone": "Asia/Kolkata"})

    matches_28 = res_28.get("matches", [])
    matches_29 = res_29.get("matches", [])
    matches_30 = res_30.get("matches", [])

    # Confirm that all 28 matches have local_date on Sep 28
    for m in matches_28:
        assert "Sep 28" in m["local_date"], f"Expected Sep 28 match, got {m['local_date']}"

    # Confirm that all 29 matches have local_date on Sep 29
    for m in matches_29:
        assert "Sep 29" in m["local_date"], f"Expected Sep 29 match, got {m['local_date']}"

    # Confirm that all 30 matches have local_date on Sep 30
    for m in matches_30:
        assert "Sep 30" in m["local_date"], f"Expected Sep 30 match, got {m['local_date']}"

    # Confirm match sets are mutually distinct
    ids_28 = {m["id"] for m in matches_28}
    ids_29 = {m["id"] for m in matches_29}
    ids_30 = {m["id"] for m in matches_30}

    assert ids_28.isdisjoint(ids_29), "Sep 28 and Sep 29 match IDs must not overlap"
    assert ids_29.isdisjoint(ids_30), "Sep 29 and Sep 30 match IDs must not overlap"


@pytest.mark.asyncio
async def test_spoken_summary_has_no_slashes_or_raw_machine_syntax():
    """Verify that spoken summary generated by sports tool never contains '/' (such as Asia/Kolkata)."""
    for d in ["2026-09-28", "2026-09-29", "2026-09-30"]:
        res = await SportsTool.fetch_fixtures({"date_from": d, "timezone": "Asia/Kolkata"})
        summary = res.get("summary", "")
        assert "/" not in summary, f"Spoken summary must not contain slash '/': {summary}"
        assert "Asia/Kolkata" not in summary, f"Spoken summary must not contain raw timezone identifier: {summary}"
        assert "{" not in summary and "}" not in summary, f"Spoken summary must not contain JSON: {summary}"


@pytest.mark.asyncio
async def test_date_range_fixtures():
    """Verify date range querying covers matches across multiple dates."""
    res_range = await SportsTool.fetch_fixtures({
        "date_from": "2026-09-28",
        "date_to": "2026-09-30",
        "timezone": "Asia/Kolkata",
    })
    matches = res_range.get("matches", [])
    assert len(matches) > 0, "Range query should return fixtures"
    dates = {m["local_date"] for m in matches}
    # Should include matches across multiple dates
    assert len(dates) >= 2, f"Expected matches spanning multiple dates, got: {dates}"


@pytest.mark.asyncio
async def test_multi_sport_intent_and_handling():
    """Verify generic intent detection and honest reporting across various sports."""
    provider = MockProvider()

    cricket_intent = await provider.determine_intent("What cricket matches are today?", current_date="2026-09-30")
    assert cricket_intent["category"] == "SPORTS_FIXTURE_QUERY"
    assert cricket_intent["sports_params"]["sport"] == "cricket"
    assert cricket_intent["sports_params"]["date_from"] == "2026-09-30"

    tennis_intent = await provider.determine_intent("What tennis matches are tomorrow?", current_date="2026-09-30")
    assert tennis_intent["category"] == "SPORTS_FIXTURE_QUERY"
    assert tennis_intent["sports_params"]["sport"] == "tennis"
    assert tennis_intent["sports_params"]["date_from"] == "2026-10-01"

    bball_intent = await provider.determine_intent("What basketball games are this weekend?", current_date="2026-09-30")
    assert bball_intent["category"] == "SPORTS_FIXTURE_QUERY"
    assert bball_intent["sports_params"]["sport"] == "basketball"
    assert bball_intent["sports_params"]["date_from"] == "2026-10-03"
    assert bball_intent["sports_params"]["date_to"] == "2026-10-04"
