"""
NEXUS LLM Provider Abstraction and Mock Implementation.

The mock provider handles planning, interruption classification, response
generation, and image analysis using deterministic logic — no API keys needed.
Real providers (Gemini, OpenAI) can be swapped in via config.
"""

from __future__ import annotations

import json
import re
from abc import ABC, abstractmethod
from typing import Any, AsyncIterator

from pydantic import BaseModel, Field

from backend.config import Settings


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

class Classification(BaseModel):
    category: str
    confidence: float = 1.0
    reasoning: str = ""
    details: dict[str, Any] = Field(default_factory=dict)


class PlanSpec(BaseModel):
    """A structured plan generated by the LLM."""
    goal_summary: str = ""
    constraints: dict[str, Any] = Field(default_factory=dict)
    tasks: list[dict[str, Any]] = Field(default_factory=list)


class Message(BaseModel):
    role: str  # "system", "user", "assistant"
    content: str


# ---------------------------------------------------------------------------
# Abstract Provider
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    name: str = "base"

    @abstractmethod
    async def generate(self, messages: list[Message], **kwargs: Any) -> str:
        """Generate a text response."""
        ...

    @abstractmethod
    async def generate_stream(self, messages: list[Message], **kwargs: Any) -> AsyncIterator[str]:
        """Stream text generation token by token."""
        ...

    @abstractmethod
    async def classify(self, text: str, categories: list[str], context: str = "") -> Classification:
        """Classify text into one of the categories."""
        ...

    @abstractmethod
    async def create_plan(self, goal: str, constraints: dict[str, Any], context: str = "") -> PlanSpec:
        """Generate a structured execution plan from a goal."""
        ...

    @abstractmethod
    async def analyze_image(self, image_data: str, prompt: str) -> str:
        """Analyze an image and return description."""
        ...

    @abstractmethod
    async def generate_response(self, task_results: list[dict], goal: str, context: str = "") -> str:
        """Generate a natural language response from task results."""
        ...


# ---------------------------------------------------------------------------
# Mock Provider — Deterministic, no API key required
# ---------------------------------------------------------------------------

class MockProvider(LLMProvider):
    """
    Deterministic mock provider for hackathon reliability.

    Uses keyword matching and rule-based logic to produce realistic
    structured outputs for planning, classification, and response
    generation without any external API calls.
    """

    name = "mock"

    async def generate(self, messages: list[Message], **kwargs: Any) -> str:
        last = messages[-1].content if messages else ""
        return f"I understand your request: {last[:100]}. Let me help you with that."

    async def generate_stream(self, messages: list[Message], **kwargs: Any) -> AsyncIterator[str]:
        response = await self.generate(messages, **kwargs)
        words = response.split()
        for word in words:
            yield word + " "

    async def classify(self, text: str, categories: list[str], context: str = "") -> Classification:
        """Classify interruptions using keyword matching."""
        text_lower = text.lower().strip()

        # Backchannel detection
        backchannels = {"yeah", "yes", "okay", "ok", "uh huh", "hmm", "right", "sure", "got it", "mhm", "yep", "alright", "fine", "cool", "cool, got it", "cool got it", "got it thanks"}
        words_in_text = set(re.findall(r"\w+", text_lower))
        if text_lower in backchannels or any(text_lower == b for b in backchannels):
            return Classification(category="BACKCHANNEL", confidence=0.95, reasoning="Short backchannel utterance")
        if all(w in {"yeah", "yes", "okay", "ok", "uh", "huh", "hmm", "right", "sure", "got", "it", "mhm", "yep", "alright", "fine", "cool", "thanks", "nice"} for w in words_in_text):
            return Classification(category="BACKCHANNEL", confidence=0.95, reasoning="Backchannel interjection")

        # Task cancellation
        cancel_patterns = ["stop", "cancel", "don't", "forget about", "skip", "remove", "drop"]
        if any(p in text_lower for p in cancel_patterns) and not any(w in text_lower for w in ["instead", "actually", "change"]):
            return Classification(category="TASK_CANCELLATION", confidence=0.85, reasoning="Cancellation keywords detected")

        # New goal explicit patterns
        new_goal_patterns = ["forget the trip", "forget about", "help me with something else", "let's do something else", "new topic", "forget everything", "start over"]
        if any(p in text_lower for p in new_goal_patterns):
            return Classification(category="NEW_GOAL", confidence=0.9, reasoning="Complete goal change detected")

        # Goal change (broader changes / modifications)
        goal_patterns = ["instead of", "rather than", "switch to", "change the plan", "different", "hostels", "hostel", "find .* instead"]
        if any(re.search(p, text_lower) for p in goal_patterns):
            return Classification(category="GOAL_CHANGE", confidence=0.85, reasoning="Goal modification detected")

        # Correction detection
        correction_patterns = ["actually", "i meant", "not that", "no,", "no ", "wrong", "i said"]
        if any(p in text_lower for p in correction_patterns):
            goal_change_hints = ["instead", "rather", "change to", "switch to", "find .* instead"]
            if any(re.search(p, text_lower) for p in goal_change_hints):
                return Classification(category="GOAL_CHANGE", confidence=0.85, reasoning="Goal change with correction pattern")
            extracted = self._extract_constraint_changes(text_lower)
            return Classification(category="CORRECTION", confidence=0.85, reasoning="Correction pattern detected", details=extracted)

        # Constraint change detection (numbers, budget, dates, people)
        constraint_patterns = [
            r"budget.*\d", r"₹\s*\d", r"rs\s*\.?\s*\d", r"\d+.*budget",
            r"\d+.*people", r"\d+.*person", r"\d+.*days?", r"\d+.*night",
            r"make it", r"change.*to", r"under \d", r"below \d",
            r"parents", r"family", r"friends", r"more people",
            r"walking", r"accessibility", r"wheelchair", r"avoid.*walking",
            r"low walking", r"less walking",
        ]
        if any(re.search(p, text_lower) for p in constraint_patterns):
            return Classification(category="CONSTRAINT_CHANGE", confidence=0.85, reasoning="Constraint modification detected",
                                  details=self._extract_constraint_changes(text_lower))

        # Question detection
        question_markers = ["why", "how", "what", "when", "where", "which", "can you explain", "tell me why", "?"]
        if any(text_lower.startswith(q) for q in ["why", "how", "what", "when", "where", "which"]) or text_lower.endswith("?"):
            return Classification(category="QUESTION", confidence=0.85, reasoning="Question pattern detected")

        # Topic pivot check: if active context is travel and user utterance introduces a non-travel domain
        travel_keywords = {"trip", "travel", "tour", "hotel", "hotels", "hostel", "hostels", "itinerary", "stay", "visit", "vacation", "holiday", "budget", "walking", "city", "chennai", "bangalore", "mumbai", "delhi", "goa", "jaipur", "hyderabad"}
        has_travel_terms = bool(words_in_text.intersection(travel_keywords))
        context_lower = context.lower()
        is_context_travel = any(k in context_lower for k in ["trip", "chennai", "hotel", "itinerary", "budget"])

        if is_context_travel and not has_travel_terms and len(words_in_text) >= 3:
            return Classification(category="NEW_GOAL", confidence=0.9, reasoning="Non-travel topic pivot detected while travel plan was active")

        # Fallback: if input has no travel keywords and is a substantial sentence, treat as new goal
        if not has_travel_terms and len(words_in_text) > 3:
            return Classification(category="NEW_GOAL", confidence=0.8, reasoning="New request/topic detected")

        # Default: treat as constraint change if it contains useful info
        if len(text_lower.split()) > 3:
            return Classification(category="CONSTRAINT_CHANGE", confidence=0.6, reasoning="Additional information provided")

        return Classification(category="BACKCHANNEL", confidence=0.5, reasoning="Short input, treating as backchannel")

    async def create_plan(self, goal: str, constraints: dict[str, Any], context: str = "") -> PlanSpec:
        """Generate a structured plan based on the goal and constraints."""
        goal_lower = goal.lower()

        # Check if this request is a travel trip goal or general query/non-travel request
        travel_keywords = ["trip", "travel", "tour", "hotel", "itinerary", "stay", "visit", "vacation", "holiday", "chennai", "bangalore", "mumbai", "delhi", "goa", "jaipur", "hyderabad"]
        is_travel_request = any(k in goal_lower for k in travel_keywords) or bool(constraints.get("city"))

        if not is_travel_request:
            tasks = [
                {
                    "id": "search_info",
                    "name": "Search information",
                    "description": f"Search for relevant information regarding: {goal}",
                    "tool": "database_query",
                    "input": {"query_type": "general_search", "query": goal},
                    "dependencies": [],
                    "priority": 10,
                },
                {
                    "id": "synthesize_response",
                    "name": "Synthesize response",
                    "description": f"Analyze findings and formulate answer for: {goal}",
                    "tool": "database_query",
                    "input": {"query_type": "synthesize", "query": goal},
                    "dependencies": ["search_info"],
                    "priority": 8,
                },
            ]
            return PlanSpec(
                goal_summary=goal,
                constraints={},
                tasks=tasks,
            )

        # Extract key parameters
        city = constraints.get("city", self._extract_city(goal_lower))
        budget = constraints.get("budget", self._extract_number(goal_lower, "budget"))
        duration = constraints.get("duration_days", self._extract_number(goal_lower, "day"))
        num_people = constraints.get("num_people", self._extract_number(goal_lower, "people"))
        max_walking = constraints.get("max_walking", None)

        if not city:
            city = "chennai"  # default for travel demo
        if not budget:
            budget = 15000
        if not duration:
            duration = 3
        if not num_people:
            num_people = 3

        plan_constraints = {
            "city": city,
            "budget": budget,
            "duration_days": duration,
            "num_people": num_people,
        }
        if max_walking:
            plan_constraints["max_walking"] = max_walking

        # Build task list
        tasks = self._build_travel_plan_tasks(city, budget, duration, num_people, max_walking)

        return PlanSpec(
            goal_summary=f"Plan a {duration}-day {city.title()} trip for {num_people} people under ₹{budget:,}",
            constraints=plan_constraints,
            tasks=tasks,
        )

    def _build_travel_plan_tasks(
        self, city: str, budget: int, duration: int, num_people: int, max_walking: str | None
    ) -> list[dict[str, Any]]:
        """Build task list for travel planning."""
        budget_per_night = int(budget * 0.35 / max(duration, 1))  # ~35% for hotel
        budget_per_person_activity = int(budget * 0.25 / max(num_people, 1))  # ~25% for activities

        tasks = [
            {
                "id": "understand_req",
                "name": "Understand requirements",
                "description": f"Analyse the travel request for {city.title()}",
                "tool": "database_query",
                "input": {"query_type": "transport", "city": city},
                "dependencies": [],
                "priority": 10,
            },
            {
                "id": "search_destinations",
                "name": "Search destinations",
                "description": f"Find tourist destinations in {city.title()}",
                "tool": "destination_search",
                "input": {
                    "city": city,
                    "max_walking": max_walking,
                    "budget_per_person": budget_per_person_activity,
                },
                "dependencies": ["understand_req"],
                "priority": 8,
            },
            {
                "id": "search_hotels",
                "name": "Search hotels",
                "description": f"Find hotels in {city.title()} within budget",
                "tool": "hotel_search",
                "input": {
                    "city": city,
                    "max_price_per_night": budget_per_night,
                    "num_nights": duration,
                    "num_rooms": max(1, (num_people + 1) // 2),
                    "min_accessibility": "good" if max_walking in ("low",) else None,
                },
                "dependencies": ["understand_req"],
                "priority": 8,
            },
            {
                "id": "search_activities",
                "name": "Search activities",
                "description": f"Find activities in {city.title()}",
                "tool": "activity_search",
                "input": {
                    "city": city,
                    "max_walking": max_walking,
                    "max_cost_per_person": budget_per_person_activity,
                },
                "dependencies": ["understand_req"],
                "priority": 7,
            },
            {
                "id": "build_itinerary",
                "name": "Build itinerary",
                "description": f"Create a {duration}-day itinerary from search results",
                "tool": "database_query",
                "input": {
                    "query_type": "itinerary_check",
                    "items": [],  # filled from previous results
                    "constraints": {"budget": budget, "max_walking": max_walking},
                },
                "dependencies": ["search_destinations", "search_hotels", "search_activities"],
                "priority": 6,
            },
            {
                "id": "calculate_budget",
                "name": "Calculate total budget",
                "description": "Calculate total trip cost and per-person breakdown",
                "tool": "budget_calculator",
                "input": {
                    "total_budget": budget,
                    "num_people": num_people,
                    "num_nights": duration,
                    "food_cost_per_day": 500,
                },
                "dependencies": ["build_itinerary"],
                "priority": 5,
            },
        ]

        return tasks

    async def analyze_image(self, image_data: str, prompt: str) -> str:
        return "The image shows what appears to be a hotel or accommodation. It looks clean and well-maintained, suitable for a budget trip."

    async def generate_response(self, task_results: list[dict], goal: str, context: str = "") -> str:
        """Generate a natural language response from task results."""
        direct_answers: list[str] = []
        travel_parts: list[str] = []
        found_any = False

        for result in task_results:
            if not isinstance(result, dict):
                continue
            output = result.get("output", {})
            status = result.get("status", "")

            if status == "COMPLETED" and output:
                if isinstance(output, dict):
                    ans = output.get("answer")
                    res = output.get("results")
                    if ans and isinstance(ans, str) and not ans.startswith("Synthesized response for:"):
                        if ans not in direct_answers:
                            direct_answers.append(ans)
                        found_any = True
                    elif res and isinstance(res, str) and not res.startswith("Retrieved current relevant information for:"):
                        if res not in direct_answers:
                            direct_answers.append(res)
                        found_any = True
                    elif "destinations" in output:
                        found_any = True
                        count = output.get("count", 0)
                        places = output.get("destinations", [])[:3]
                        p_names = [p.get("name", str(p)) if isinstance(p, dict) else str(p) for p in places if p]
                        travel_parts.append(f"🏛️ Found {count} destinations. Top picks: {', '.join(p_names)}")
                    elif "hotels" in output:
                        found_any = True
                        count = output.get("count", 0)
                        hotels = output.get("hotels", [])[:3]
                        h_names = [h.get("name", str(h)) if isinstance(h, dict) else str(h) for h in hotels if h]
                        travel_parts.append(f"🏨 Found {count} hotels. Best rated: {', '.join(h_names)}")
                    elif "activities" in output:
                        found_any = True
                        count = output.get("count", 0)
                        acts = output.get("activities", [])[:3]
                        a_names = [a.get("name", str(a)) if isinstance(a, dict) else str(a) for a in acts if a]
                        travel_parts.append(f"🎯 Found {count} activities. Highlights: {', '.join(a_names)}")
                    elif "total_estimated" in output:
                        found_any = True
                        total = output.get("total_estimated", 0)
                        per_person = output.get("per_person", 0)
                        within = output.get("within_budget", True)
                        status_text = "within budget ✅" if within else "over budget ⚠️"
                        travel_parts.append(f"💰 Total estimated: ₹{total:,.0f} (₹{per_person:,.0f}/person) — {status_text}")
                else:
                    found_any = True
                    direct_answers.append(str(output))

        if direct_answers:
            return "\n".join(direct_answers)
        elif travel_parts:
            return f"I've completed planning for your request: {goal}\n" + "\n".join(travel_parts)
        elif found_any:
            return f"I analyzed your request regarding '{goal}'. In offline Mock Mode, answers are available for curated test queries. To get live dynamic answers for any random question, set GOOGLE_API_KEY in .env."
        else:
            return f"I processed your request regarding '{goal}'. To get live dynamic answers for any random question, set GOOGLE_API_KEY in .env."

    # -- Helpers -----------------------------------------------------------

    def _extract_city(self, text: str) -> str:
        cities = ["chennai", "bangalore", "mumbai", "delhi", "hyderabad", "kolkata", "goa", "jaipur", "pune", "kochi"]
        for city in cities:
            if city in text:
                return city
        return ""

    def _extract_number(self, text: str, context_word: str) -> int | None:
        # Look for numbers near the context word
        patterns = [
            rf"(\d[\d,]*)\s*(?:rs\.?|₹)?\s*{context_word}",
            rf"{context_word}\s*(?:rs\.?|₹)?\s*(\d[\d,]*)",
            rf"(?:rs\.?|₹)\s*(\d[\d,]*)",
            rf"(\d+)\s*{context_word}",
            rf"under\s*(?:rs\.?|₹)?\s*(\d[\d,]*)",
        ]
        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                return int(match.group(1).replace(",", ""))
        # Generic number extraction
        numbers = re.findall(r"\d[\d,]*", text)
        for n in numbers:
            val = int(n.replace(",", ""))
            if context_word == "budget" and val >= 1000:
                return val
            elif context_word == "day" and 1 <= val <= 30:
                return val
            elif context_word == "people" and 1 <= val <= 20:
                return val
        return None

    def _extract_constraint_changes(self, text: str) -> dict[str, Any]:
        """Extract what constraints changed from the interruption text."""
        changes: dict[str, Any] = {}

        # Budget changes
        budget_match = re.search(r"(?:budget|₹|rs\.?)\s*(?:to|is|of|under|at)?\s*(\d[\d,]*)", text)
        if not budget_match:
            budget_match = re.search(r"(\d[\d,]*)\s*(?:budget|₹|rs\.?)", text)
        if budget_match:
            changes["budget"] = int(budget_match.group(1).replace(",", ""))

        # People changes
        if "parent" in text or "family" in text:
            changes["num_people_delta"] = 2  # parents = +2
            changes["reason"] = "parents joining"
        people_match = re.search(r"(\d+)\s*(?:people|person|traveller)", text)
        if people_match:
            changes["num_people"] = int(people_match.group(1))

        # Duration changes
        day_match = re.search(r"(\d+)\s*(?:day|night)", text)
        if day_match:
            changes["duration_days"] = int(day_match.group(1))

        # Walking/accessibility
        if "walking" in text or "accessibility" in text or "wheelchair" in text:
            if "avoid" in text or "no " in text or "less" in text or "low" in text:
                changes["max_walking"] = "low"
            elif "moderate" in text:
                changes["max_walking"] = "moderate"

        # City changes
        for city in ["chennai", "bangalore", "mumbai", "delhi", "goa", "hyderabad"]:
            if city in text:
                changes["city"] = city

        return changes


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def create_provider(provider_name: str | None = None) -> LLMProvider:
    """Create an LLM provider by name.

    The default resolves from runtime configuration so provider selection is driven
    by environment or config, not by hardcoded values.
    """
    selected_provider = Settings.normalize_provider_name(provider_name or Settings.LLM_PROVIDER)
    Settings.validate_provider_config(
        selected_provider,
        api_key=Settings.GOOGLE_API_KEY,
        model_name=Settings.GEMINI_MODEL,
    )

    if selected_provider in {"gemini", "google_gemini"}:
        from backend.providers.google_gemini import GeminiProvider
        return GeminiProvider(api_key=Settings.GOOGLE_API_KEY, model=Settings.GEMINI_MODEL)
    if selected_provider == "mock":
        return MockProvider()

    raise ValueError(f"Unsupported LLM provider: {selected_provider!r}. Supported values: mock, gemini, google_gemini")
